module TestMatchesFilter
  def test_filter_matches_all
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'all', "Group Stages"=>"tournament_stage", "Round of 16"=>"tournament_stage", "Quarter Finals"=>"tournament_stage", "Semi Finals"=>"tournament_stage", "Third Fourth Place Play-off"=>"tournament_stage", "Final"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    assert_includes last_response.body, '<td hidden>1</td>'
    assert_includes last_response.body, '<td hidden>2</td>'
    assert_includes last_response.body, '<td hidden>3</td>'
    assert_includes last_response.body, '<td hidden>4</td>'
    assert_includes last_response.body, '<td hidden>5</td>'
    assert_includes last_response.body, '<td hidden>6</td>'
    assert_includes last_response.body, '<td hidden>7</td>'
    assert_includes last_response.body, '<td hidden>8</td>'
    assert_includes last_response.body, '<td hidden>9</td>'
    assert_includes last_response.body, '<td hidden>10</td>'
    assert_includes last_response.body, '<td hidden>11</td>'
    assert_includes last_response.body, '<td hidden>12</td>'
    assert_includes last_response.body, '<td hidden>13</td>'
    assert_includes last_response.body, '<td hidden>14</td>'
    assert_includes last_response.body, '<td hidden>15</td>'
    assert_includes last_response.body, '<td hidden>16</td>'
    assert_includes last_response.body, '<td hidden>17</td>'
    assert_includes last_response.body, '<td hidden>18</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>21</td>'
    assert_includes last_response.body, '<td hidden>22</td>'
    assert_includes last_response.body, '<td hidden>23</td>'
    assert_includes last_response.body, '<td hidden>24</td>'
    assert_includes last_response.body, '<td hidden>25</td>'
    assert_includes last_response.body, '<td hidden>26</td>'
    assert_includes last_response.body, '<td hidden>27</td>'
    assert_includes last_response.body, '<td hidden>28</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>31</td>'
    assert_includes last_response.body, '<td hidden>32</td>'
    assert_includes last_response.body, '<td hidden>33</td>'
    assert_includes last_response.body, '<td hidden>34</td>'
    assert_includes last_response.body, '<td hidden>35</td>'
    assert_includes last_response.body, '<td hidden>36</td>'
    assert_includes last_response.body, '<td hidden>37</td>'
    assert_includes last_response.body, '<td hidden>38</td>'
    assert_includes last_response.body, '<td hidden>39</td>'
    assert_includes last_response.body, '<td hidden>40</td>'
    assert_includes last_response.body, '<td hidden>41</td>'
    assert_includes last_response.body, '<td hidden>42</td>'
    assert_includes last_response.body, '<td hidden>43</td>'
    assert_includes last_response.body, '<td hidden>44</td>'
    assert_includes last_response.body, '<td hidden>45</td>'
    assert_includes last_response.body, '<td hidden>46</td>'
    assert_includes last_response.body, '<td hidden>47</td>'
    assert_includes last_response.body, '<td hidden>48</td>'
    assert_includes last_response.body, '<td hidden>49</td>'
    assert_includes last_response.body, '<td hidden>50</td>'
    assert_includes last_response.body, '<td hidden>51</td>'
    assert_includes last_response.body, '<td hidden>52</td>'
    assert_includes last_response.body, '<td hidden>53</td>'
    assert_includes last_response.body, '<td hidden>54</td>'
    assert_includes last_response.body, '<td hidden>55</td>'
    assert_includes last_response.body, '<td hidden>56</td>'
    assert_includes last_response.body, '<td hidden>57</td>'
    assert_includes last_response.body, '<td hidden>58</td>'
    assert_includes last_response.body, '<td hidden>59</td>'
    assert_includes last_response.body, '<td hidden>60</td>'
    assert_includes last_response.body, '<td hidden>61</td>'
    assert_includes last_response.body, '<td hidden>62</td>'
    assert_includes last_response.body, '<td hidden>63</td>'
    assert_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_locked_down
    post '/matches/filter',
      {match_status: 'locked_down', prediction_status: 'all', "Group Stages"=>"tournament_stage", "Round of 16"=>"tournament_stage", "Quarter Finals"=>"tournament_stage", "Semi Finals"=>"tournament_stage", "Third Fourth Place Play-off"=>"tournament_stage", "Final"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    assert_includes last_response.body, '<td hidden>1</td>'
    assert_includes last_response.body, '<td hidden>2</td>'
    assert_includes last_response.body, '<td hidden>3</td>'
    assert_includes last_response.body, '<td hidden>4</td>'
    assert_includes last_response.body, '<td hidden>5</td>'
    assert_includes last_response.body, '<td hidden>6</td>'
    assert_includes last_response.body, '<td hidden>7</td>'
    assert_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    refute_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_not_locked_down
    post '/matches/filter',
      {match_status: 'not_locked_down', prediction_status: 'all', "Group Stages"=>"tournament_stage", "Round of 16"=>"tournament_stage", "Quarter Finals"=>"tournament_stage", "Semi Finals"=>"tournament_stage", "Third Fourth Place Play-off"=>"tournament_stage", "Final"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    refute_includes last_response.body, '<td hidden>6</td>'
    refute_includes last_response.body, '<td hidden>7</td>'
    refute_includes last_response.body, '<td hidden>8</td>'
    assert_includes last_response.body, '<td hidden>9</td>'
    assert_includes last_response.body, '<td hidden>10</td>'
    assert_includes last_response.body, '<td hidden>11</td>'
    assert_includes last_response.body, '<td hidden>12</td>'
    assert_includes last_response.body, '<td hidden>13</td>'
    assert_includes last_response.body, '<td hidden>14</td>'
    assert_includes last_response.body, '<td hidden>15</td>'
    assert_includes last_response.body, '<td hidden>16</td>'
    assert_includes last_response.body, '<td hidden>17</td>'
    assert_includes last_response.body, '<td hidden>18</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>21</td>'
    assert_includes last_response.body, '<td hidden>22</td>'
    assert_includes last_response.body, '<td hidden>23</td>'
    assert_includes last_response.body, '<td hidden>24</td>'
    assert_includes last_response.body, '<td hidden>25</td>'
    assert_includes last_response.body, '<td hidden>26</td>'
    assert_includes last_response.body, '<td hidden>27</td>'
    assert_includes last_response.body, '<td hidden>28</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>31</td>'
    assert_includes last_response.body, '<td hidden>32</td>'
    assert_includes last_response.body, '<td hidden>33</td>'
    assert_includes last_response.body, '<td hidden>34</td>'
    assert_includes last_response.body, '<td hidden>35</td>'
    assert_includes last_response.body, '<td hidden>36</td>'
    assert_includes last_response.body, '<td hidden>37</td>'
    assert_includes last_response.body, '<td hidden>38</td>'
    assert_includes last_response.body, '<td hidden>39</td>'
    assert_includes last_response.body, '<td hidden>40</td>'
    assert_includes last_response.body, '<td hidden>41</td>'
    assert_includes last_response.body, '<td hidden>42</td>'
    assert_includes last_response.body, '<td hidden>43</td>'
    assert_includes last_response.body, '<td hidden>44</td>'
    assert_includes last_response.body, '<td hidden>45</td>'
    assert_includes last_response.body, '<td hidden>46</td>'
    assert_includes last_response.body, '<td hidden>47</td>'
    assert_includes last_response.body, '<td hidden>48</td>'
    assert_includes last_response.body, '<td hidden>49</td>'
    assert_includes last_response.body, '<td hidden>50</td>'
    assert_includes last_response.body, '<td hidden>51</td>'
    assert_includes last_response.body, '<td hidden>52</td>'
    assert_includes last_response.body, '<td hidden>53</td>'
    assert_includes last_response.body, '<td hidden>54</td>'
    assert_includes last_response.body, '<td hidden>55</td>'
    assert_includes last_response.body, '<td hidden>56</td>'
    assert_includes last_response.body, '<td hidden>57</td>'
    assert_includes last_response.body, '<td hidden>58</td>'
    assert_includes last_response.body, '<td hidden>59</td>'
    assert_includes last_response.body, '<td hidden>60</td>'
    assert_includes last_response.body, '<td hidden>61</td>'
    assert_includes last_response.body, '<td hidden>62</td>'
    assert_includes last_response.body, '<td hidden>63</td>'
    assert_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_predicted
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'predicted', "Group Stages"=>"tournament_stage", "Round of 16"=>"tournament_stage", "Quarter Finals"=>"tournament_stage", "Semi Finals"=>"tournament_stage", "Third Fourth Place Play-off"=>"tournament_stage", "Final"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    assert_includes last_response.body, '<td hidden>6</td>'
    assert_includes last_response.body, '<td hidden>7</td>'
    assert_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    assert_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_not_predicted
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'not_predicted', "Group Stages"=>"tournament_stage", "Round of 16"=>"tournament_stage", "Quarter Finals"=>"tournament_stage", "Semi Finals"=>"tournament_stage", "Third Fourth Place Play-off"=>"tournament_stage", "Final"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    assert_includes last_response.body, '<td hidden>1</td>'
    assert_includes last_response.body, '<td hidden>2</td>'
    assert_includes last_response.body, '<td hidden>3</td>'
    assert_includes last_response.body, '<td hidden>4</td>'
    assert_includes last_response.body, '<td hidden>5</td>'
    refute_includes last_response.body, '<td hidden>6</td>'
    refute_includes last_response.body, '<td hidden>7</td>'
    refute_includes last_response.body, '<td hidden>8</td>'
    assert_includes last_response.body, '<td hidden>9</td>'
    assert_includes last_response.body, '<td hidden>10</td>'
    refute_includes last_response.body, '<td hidden>11</td>'
    assert_includes last_response.body, '<td hidden>12</td>'
    assert_includes last_response.body, '<td hidden>13</td>'
    assert_includes last_response.body, '<td hidden>14</td>'
    assert_includes last_response.body, '<td hidden>15</td>'
    assert_includes last_response.body, '<td hidden>16</td>'
    assert_includes last_response.body, '<td hidden>17</td>'
    assert_includes last_response.body, '<td hidden>18</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>21</td>'
    assert_includes last_response.body, '<td hidden>22</td>'
    assert_includes last_response.body, '<td hidden>23</td>'
    assert_includes last_response.body, '<td hidden>24</td>'
    assert_includes last_response.body, '<td hidden>25</td>'
    assert_includes last_response.body, '<td hidden>26</td>'
    assert_includes last_response.body, '<td hidden>27</td>'
    assert_includes last_response.body, '<td hidden>28</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>31</td>'
    assert_includes last_response.body, '<td hidden>32</td>'
    assert_includes last_response.body, '<td hidden>33</td>'
    assert_includes last_response.body, '<td hidden>34</td>'
    assert_includes last_response.body, '<td hidden>35</td>'
    assert_includes last_response.body, '<td hidden>36</td>'
    assert_includes last_response.body, '<td hidden>37</td>'
    assert_includes last_response.body, '<td hidden>38</td>'
    assert_includes last_response.body, '<td hidden>39</td>'
    assert_includes last_response.body, '<td hidden>40</td>'
    assert_includes last_response.body, '<td hidden>41</td>'
    assert_includes last_response.body, '<td hidden>42</td>'
    assert_includes last_response.body, '<td hidden>43</td>'
    assert_includes last_response.body, '<td hidden>44</td>'
    assert_includes last_response.body, '<td hidden>45</td>'
    assert_includes last_response.body, '<td hidden>46</td>'
    assert_includes last_response.body, '<td hidden>47</td>'
    assert_includes last_response.body, '<td hidden>48</td>'
    assert_includes last_response.body, '<td hidden>49</td>'
    assert_includes last_response.body, '<td hidden>50</td>'
    assert_includes last_response.body, '<td hidden>51</td>'
    assert_includes last_response.body, '<td hidden>52</td>'
    assert_includes last_response.body, '<td hidden>53</td>'
    assert_includes last_response.body, '<td hidden>54</td>'
    assert_includes last_response.body, '<td hidden>55</td>'
    assert_includes last_response.body, '<td hidden>56</td>'
    assert_includes last_response.body, '<td hidden>57</td>'
    assert_includes last_response.body, '<td hidden>58</td>'
    assert_includes last_response.body, '<td hidden>59</td>'
    assert_includes last_response.body, '<td hidden>60</td>'
    assert_includes last_response.body, '<td hidden>61</td>'
    assert_includes last_response.body, '<td hidden>62</td>'
    assert_includes last_response.body, '<td hidden>63</td>'
    assert_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_group_stages
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'all', "Group Stages"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    assert_includes last_response.body, '<td hidden>1</td>'
    assert_includes last_response.body, '<td hidden>2</td>'
    assert_includes last_response.body, '<td hidden>3</td>'
    assert_includes last_response.body, '<td hidden>4</td>'
    assert_includes last_response.body, '<td hidden>5</td>'
    assert_includes last_response.body, '<td hidden>6</td>'
    assert_includes last_response.body, '<td hidden>7</td>'
    assert_includes last_response.body, '<td hidden>8</td>'
    assert_includes last_response.body, '<td hidden>9</td>'
    assert_includes last_response.body, '<td hidden>10</td>'
    assert_includes last_response.body, '<td hidden>11</td>'
    assert_includes last_response.body, '<td hidden>12</td>'
    assert_includes last_response.body, '<td hidden>13</td>'
    assert_includes last_response.body, '<td hidden>14</td>'
    assert_includes last_response.body, '<td hidden>15</td>'
    assert_includes last_response.body, '<td hidden>16</td>'
    assert_includes last_response.body, '<td hidden>17</td>'
    assert_includes last_response.body, '<td hidden>18</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>21</td>'
    assert_includes last_response.body, '<td hidden>22</td>'
    assert_includes last_response.body, '<td hidden>23</td>'
    assert_includes last_response.body, '<td hidden>24</td>'
    assert_includes last_response.body, '<td hidden>25</td>'
    assert_includes last_response.body, '<td hidden>26</td>'
    assert_includes last_response.body, '<td hidden>27</td>'
    assert_includes last_response.body, '<td hidden>28</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>31</td>'
    assert_includes last_response.body, '<td hidden>32</td>'
    assert_includes last_response.body, '<td hidden>33</td>'
    assert_includes last_response.body, '<td hidden>34</td>'
    assert_includes last_response.body, '<td hidden>35</td>'
    assert_includes last_response.body, '<td hidden>36</td>'
    assert_includes last_response.body, '<td hidden>37</td>'
    assert_includes last_response.body, '<td hidden>38</td>'
    assert_includes last_response.body, '<td hidden>39</td>'
    assert_includes last_response.body, '<td hidden>40</td>'
    assert_includes last_response.body, '<td hidden>41</td>'
    assert_includes last_response.body, '<td hidden>42</td>'
    assert_includes last_response.body, '<td hidden>43</td>'
    assert_includes last_response.body, '<td hidden>44</td>'
    assert_includes last_response.body, '<td hidden>45</td>'
    assert_includes last_response.body, '<td hidden>46</td>'
    assert_includes last_response.body, '<td hidden>47</td>'
    assert_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_round_of_16
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'all', "Round of 16"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    refute_includes last_response.body, '<td hidden>6</td>'
    refute_includes last_response.body, '<td hidden>7</td>'
    refute_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    refute_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    assert_includes last_response.body, '<td hidden>49</td>'
    assert_includes last_response.body, '<td hidden>50</td>'
    assert_includes last_response.body, '<td hidden>51</td>'
    assert_includes last_response.body, '<td hidden>52</td>'
    assert_includes last_response.body, '<td hidden>53</td>'
    assert_includes last_response.body, '<td hidden>54</td>'
    assert_includes last_response.body, '<td hidden>55</td>'
    assert_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_quarter_finals
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'all', "Quarter Finals"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    refute_includes last_response.body, '<td hidden>6</td>'
    refute_includes last_response.body, '<td hidden>7</td>'
    refute_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    refute_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    assert_includes last_response.body, '<td hidden>57</td>'
    assert_includes last_response.body, '<td hidden>58</td>'
    assert_includes last_response.body, '<td hidden>59</td>'
    assert_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end
   
  def test_filter_matches_semi_finals
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'all', "Semi Finals"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    refute_includes last_response.body, '<td hidden>6</td>'
    refute_includes last_response.body, '<td hidden>7</td>'
    refute_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    refute_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    assert_includes last_response.body, '<td hidden>61</td>'
    assert_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_3_4_place
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'all', "Third Fourth Place Play-off"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    refute_includes last_response.body, '<td hidden>6</td>'
    refute_includes last_response.body, '<td hidden>7</td>'
    refute_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    refute_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    assert_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_final
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'all', "Final"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    refute_includes last_response.body, '<td hidden>6</td>'
    refute_includes last_response.body, '<td hidden>7</td>'
    refute_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    refute_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    assert_includes last_response.body, '<td hidden>64</td>'
  end
  
def test_filter_matches_group_stages_and_final
    post '/matches/filter',
      {match_status: 'all', prediction_status: 'all', "Group Stages"=>"tournament_stage", "Final"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    assert_includes last_response.body, '<td hidden>1</td>'
    assert_includes last_response.body, '<td hidden>2</td>'
    assert_includes last_response.body, '<td hidden>3</td>'
    assert_includes last_response.body, '<td hidden>4</td>'
    assert_includes last_response.body, '<td hidden>5</td>'
    assert_includes last_response.body, '<td hidden>6</td>'
    assert_includes last_response.body, '<td hidden>7</td>'
    assert_includes last_response.body, '<td hidden>8</td>'
    assert_includes last_response.body, '<td hidden>9</td>'
    assert_includes last_response.body, '<td hidden>10</td>'
    assert_includes last_response.body, '<td hidden>11</td>'
    assert_includes last_response.body, '<td hidden>12</td>'
    assert_includes last_response.body, '<td hidden>13</td>'
    assert_includes last_response.body, '<td hidden>14</td>'
    assert_includes last_response.body, '<td hidden>15</td>'
    assert_includes last_response.body, '<td hidden>16</td>'
    assert_includes last_response.body, '<td hidden>17</td>'
    assert_includes last_response.body, '<td hidden>18</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>21</td>'
    assert_includes last_response.body, '<td hidden>22</td>'
    assert_includes last_response.body, '<td hidden>23</td>'
    assert_includes last_response.body, '<td hidden>24</td>'
    assert_includes last_response.body, '<td hidden>25</td>'
    assert_includes last_response.body, '<td hidden>26</td>'
    assert_includes last_response.body, '<td hidden>27</td>'
    assert_includes last_response.body, '<td hidden>28</td>'
    assert_includes last_response.body, '<td hidden>29</td>'
    assert_includes last_response.body, '<td hidden>20</td>'
    assert_includes last_response.body, '<td hidden>31</td>'
    assert_includes last_response.body, '<td hidden>32</td>'
    assert_includes last_response.body, '<td hidden>33</td>'
    assert_includes last_response.body, '<td hidden>34</td>'
    assert_includes last_response.body, '<td hidden>35</td>'
    assert_includes last_response.body, '<td hidden>36</td>'
    assert_includes last_response.body, '<td hidden>37</td>'
    assert_includes last_response.body, '<td hidden>38</td>'
    assert_includes last_response.body, '<td hidden>39</td>'
    assert_includes last_response.body, '<td hidden>40</td>'
    assert_includes last_response.body, '<td hidden>41</td>'
    assert_includes last_response.body, '<td hidden>42</td>'
    assert_includes last_response.body, '<td hidden>43</td>'
    assert_includes last_response.body, '<td hidden>44</td>'
    assert_includes last_response.body, '<td hidden>45</td>'
    assert_includes last_response.body, '<td hidden>46</td>'
    assert_includes last_response.body, '<td hidden>47</td>'
    assert_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    assert_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_not_locked_down_predicted_group_stages
    post '/matches/filter',
      {match_status: 'not_locked_down', prediction_status: 'predicted', "Group Stages"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    refute_includes last_response.body, '<td hidden>6</td>'
    refute_includes last_response.body, '<td hidden>7</td>'
    refute_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    assert_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end
  
  def test_filter_matches_locked_down_predicted_group_stages
    post '/matches/filter',
      {match_status: 'locked_down', prediction_status: 'predicted', "Group Stages"=>"tournament_stage"},
      user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, 'Matches List'
    refute_includes last_response.body, '<td hidden>1</td>'
    refute_includes last_response.body, '<td hidden>2</td>'
    refute_includes last_response.body, '<td hidden>3</td>'
    refute_includes last_response.body, '<td hidden>4</td>'
    refute_includes last_response.body, '<td hidden>5</td>'
    assert_includes last_response.body, '<td hidden>6</td>'
    assert_includes last_response.body, '<td hidden>7</td>'
    assert_includes last_response.body, '<td hidden>8</td>'
    refute_includes last_response.body, '<td hidden>9</td>'
    refute_includes last_response.body, '<td hidden>10</td>'
    refute_includes last_response.body, '<td hidden>11</td>'
    refute_includes last_response.body, '<td hidden>12</td>'
    refute_includes last_response.body, '<td hidden>13</td>'
    refute_includes last_response.body, '<td hidden>14</td>'
    refute_includes last_response.body, '<td hidden>15</td>'
    refute_includes last_response.body, '<td hidden>16</td>'
    refute_includes last_response.body, '<td hidden>17</td>'
    refute_includes last_response.body, '<td hidden>18</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>21</td>'
    refute_includes last_response.body, '<td hidden>22</td>'
    refute_includes last_response.body, '<td hidden>23</td>'
    refute_includes last_response.body, '<td hidden>24</td>'
    refute_includes last_response.body, '<td hidden>25</td>'
    refute_includes last_response.body, '<td hidden>26</td>'
    refute_includes last_response.body, '<td hidden>27</td>'
    refute_includes last_response.body, '<td hidden>28</td>'
    refute_includes last_response.body, '<td hidden>29</td>'
    refute_includes last_response.body, '<td hidden>20</td>'
    refute_includes last_response.body, '<td hidden>31</td>'
    refute_includes last_response.body, '<td hidden>32</td>'
    refute_includes last_response.body, '<td hidden>33</td>'
    refute_includes last_response.body, '<td hidden>34</td>'
    refute_includes last_response.body, '<td hidden>35</td>'
    refute_includes last_response.body, '<td hidden>36</td>'
    refute_includes last_response.body, '<td hidden>37</td>'
    refute_includes last_response.body, '<td hidden>38</td>'
    refute_includes last_response.body, '<td hidden>39</td>'
    refute_includes last_response.body, '<td hidden>40</td>'
    refute_includes last_response.body, '<td hidden>41</td>'
    refute_includes last_response.body, '<td hidden>42</td>'
    refute_includes last_response.body, '<td hidden>43</td>'
    refute_includes last_response.body, '<td hidden>44</td>'
    refute_includes last_response.body, '<td hidden>45</td>'
    refute_includes last_response.body, '<td hidden>46</td>'
    refute_includes last_response.body, '<td hidden>47</td>'
    refute_includes last_response.body, '<td hidden>48</td>'
    refute_includes last_response.body, '<td hidden>49</td>'
    refute_includes last_response.body, '<td hidden>50</td>'
    refute_includes last_response.body, '<td hidden>51</td>'
    refute_includes last_response.body, '<td hidden>52</td>'
    refute_includes last_response.body, '<td hidden>53</td>'
    refute_includes last_response.body, '<td hidden>54</td>'
    refute_includes last_response.body, '<td hidden>55</td>'
    refute_includes last_response.body, '<td hidden>56</td>'
    refute_includes last_response.body, '<td hidden>57</td>'
    refute_includes last_response.body, '<td hidden>58</td>'
    refute_includes last_response.body, '<td hidden>59</td>'
    refute_includes last_response.body, '<td hidden>60</td>'
    refute_includes last_response.body, '<td hidden>61</td>'
    refute_includes last_response.body, '<td hidden>62</td>'
    refute_includes last_response.body, '<td hidden>63</td>'
    refute_includes last_response.body, '<td hidden>64</td>'
  end

  def test_filter_matches_search_criteria_retained
    post '/matches/filter',
      {match_status: 'locked_down', prediction_status: 'predicted', "Group Stages"=>"tournament_stage"},
      user_11_session

    assert_includes last_response.body.gsub(/\n/, ''), %q(value="locked_down"     checked)
    assert_includes last_response.body.gsub(/\n/, ''), %q(value="predicted"     checked)
    assert_includes last_response.body.gsub(/\n/, ''), %q(name="Group Stages"      value="tournament_stage"      checked)
    refute_includes last_response.body.gsub(/\n/, ''), %q(name="Final"      value="tournament_stage"      checked)
  end

  def test_filter_matches_no_matches_returned
    post '/matches/filter',
      {match_status: 'locked_down', prediction_status: 'all', "Final"=>"tournament_stage"},
      user_11_session

    assert_includes last_response.body, 'No matches meet your criteria, please try again!'
    refute_includes last_response.body, 'Matches List'
  end
end
